services:
  todo-app:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - 5173:5173
    volumes:
      - .:/app
    working_dir: /app
    command: ["npm", "run", "dev", "--", "--host", "0.0.0.0"]